[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'html', 'markdown']
hook_source ='''
  let g:prettier#autoformat = 1
	let g:prettier#autoformat_require_pragma = 0
'''
