[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'
merged = 0

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
merged = 0

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

